### ISSUE TITLE
unibilium-shim.cr dependency can't be found

### ISSUE THREAD

**Issue by jirihalbych** [crystallabs/crysterm#37]
While trying to install the shard, the dependency of unibilium-shim.cr can't be fulfilled, as the repository no longer exists.

Failed to clone https://github.com/crystallabs/unibilium-shim.cr.git: Failed git clone -c core.askPass=true -c init.templateDir= --mirror --quiet -- https://github.com/crystallabs/unibilium-shim.cr.git /home/ren/.cache/shards/github.com/crystallabs/unibilium-shim.cr.git.
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/crystallabs/unibilium-shim.cr.git/'

**Comment by soanvig** [comment]
```
dependencies:
  crysterm:
    github: crystallabs/crysterm
    branch: master
```

+ `shards install` works for me
